using Pkg

Pkg.add("CUDA")
Pkg.add("cuDNN")
Pkg.add("KernelAbstractions")
Pkg.add("NNlib")
Pkg.add("Tullio")
Pkg.add("Lux")
Pkg.add("LuxCUDA")
Pkg.add("LinearAlgebra")
Pkg.add("Statistics")
Pkg.add("Random")
Pkg.add("Test")
Pkg.add("ConfParser")
Pkg.add("Zygote")
Pkg.add("Distributions")
Pkg.add("Flux")
Pkg.add("Accessors")
Pkg.add("Statistics")